/**
 * BCI Threat Model tool — generate structured threat assessments for BCI devices.
 */

import { getTara, getSecurityControls } from "../data/loader.js";
import { assertNoInjection } from "../security/injection.js";
import { sanitizeReport } from "../security/sanitizer.js";
import type { BciThreatModelInput } from "../security/validator.js";
import type { TaraTechnique, ToolResult } from "../types/index.js";

const DISCLAIMER =
  "\n\n---\n*This threat model is generated by a proposed research tool (QIF/TARA, unvalidated, in development). " +
  "Not a substitute for professional security assessment. " +
  "Threat descriptions are for defensive purposes only (G7: Dual-Use Trap). " +
  "Current vs. projected capabilities are distinguished per G6: Brain Reading Limits.*";

// Device class to relevant QIF bands mapping
const DEVICE_BANDS: Record<string, string[]> = {
  consumer_eeg: ["S1", "S2", "S3"],
  research_eeg: ["S1", "S2", "S3", "I0"],
  implanted_bci: ["I0", "N1", "N2", "N3", "N4", "N5", "N6", "N7", "S1", "S2"],
  neurostimulation: ["I0", "N1", "N2", "N3", "N4", "N5", "S1", "S2"],
  neurofeedback: ["S1", "S2", "S3", "N6", "N7"],
  other: ["S1", "S2", "S3"],
};

// Connectivity to attack surface mapping
const CONNECTIVITY_RISKS: Record<string, string> = {
  bluetooth_classic: "BT Classic — susceptible to sniffing, MITM, brute-force pairing",
  ble: "BLE — limited encryption key size, susceptible to GATT enumeration",
  wifi: "WiFi — standard network attack surface (ARP spoofing, deauth, MITM)",
  usb: "USB — physical access vector, firmware injection via malicious USB",
  cloud_api: "Cloud API — API key exposure, MITM, data exfiltration, cross-border transfer",
  wired_only: "Wired — minimal wireless attack surface, physical access required",
};

function filterTechniques(
  techniques: TaraTechnique[],
  bands: string[],
  _connectivity: string[]
): TaraTechnique[] {
  return techniques.filter((t) => {
    // Check if technique bands overlap with device bands
    const techBands = t.bands.split(/[–\-]/).map((b) => b.trim());
    return techBands.some((tb) => bands.some((db) => tb.includes(db)));
  });
}

export function bciThreatModel(input: BciThreatModelInput): ToolResult {
  if (input.device_name) {
    assertNoInjection(input.device_name, "device_name");
  }
  for (const sig of input.signal_types) {
    assertNoInjection(sig, "signal_types");
  }

  const tara = getTara();
  const controls = getSecurityControls();
  const deviceBands = DEVICE_BANDS[input.device_class] ?? DEVICE_BANDS["other"];

  // Filter relevant techniques
  const relevantTechniques = filterTechniques(
    tara.techniques,
    deviceBands,
    input.connectivity
  );

  // Sort by NISS score descending, take top 15
  const topThreats = relevantTechniques
    .sort((a, b) => b.niss.score - a.niss.score)
    .slice(0, 15);

  // Build report
  const deviceLabel = input.device_name ?? input.device_class;

  let report = `## BCI Threat Model: ${deviceLabel}\n\n`;

  // Device profile
  report +=
    `### Device Profile\n\n` +
    `- **Class:** ${input.device_class}\n` +
    `- **Signal Types:** ${input.signal_types.join(", ")}\n` +
    `- **Connectivity:** ${input.connectivity.join(", ")}\n` +
    `- **Deployment:** ${input.deployment_context}\n` +
    `- **Relevant QIF Bands:** ${deviceBands.join(", ")}\n`;

  if (input.existing_controls && input.existing_controls.length > 0) {
    report += `- **Existing Controls:** ${input.existing_controls.join(", ")}\n`;
  }
  report += "\n";

  // Attack surface
  report += `### Attack Surface\n\n`;
  for (const conn of input.connectivity) {
    report += `- ${CONNECTIVITY_RISKS[conn] ?? conn}\n`;
  }
  report += "\n";

  // Top threats
  report += `### Top ${topThreats.length} Threats (by NISS score)\n\n`;
  report += "| # | ID | Technique | NISS | Severity | Status | Dual-Use |\n";
  report += "|---|-----|-----------|------|----------|--------|----------|\n";

  for (let i = 0; i < topThreats.length; i++) {
    const t = topThreats[i];
    report +=
      `| ${i + 1} | ${t.id} | ${t.name} | ${t.niss.score} (${t.niss.severity}) ` +
      `| ${t.severity} | ${t.status} | ${t.dual_use} |\n`;
  }
  report += "\n";

  // Detailed threat descriptions (top 5)
  report += `### Threat Details (Top 5)\n\n`;
  for (const t of topThreats.slice(0, 5)) {
    report +=
      `#### ${t.id}: ${t.name}\n\n` +
      `- **Mechanism:** ${t.mechanism}\n` +
      `- **Bands:** ${t.bands}\n` +
      `- **NISS Vector:** ${t.niss.vector}\n` +
      `- **Sources:** ${t.sources.join(", ")}\n`;

    if (t.dual_use !== "none") {
      report += `- **Dual-Use Note:** Therapeutic analog: ${t.therapeutic_analog}. ` +
        `The boundary is consent, dosage, and oversight — not the mechanism itself.\n`;
    }

    report += `- **Mitigations:** ${t.mitigations.join(", ")}\n\n`;
  }

  // Recommended controls by band
  report += `### Recommended Controls\n\n`;
  for (const band of deviceBands) {
    const bandControls = controls.controls_by_band[band];
    if (!bandControls) continue;

    report +=
      `#### Band ${band}\n` +
      `- **Detection:** ${bandControls.detection.join("; ")}\n` +
      `- **Prevention:** ${bandControls.prevention.join("; ")}\n` +
      `- **Response:** ${bandControls.response.join("; ")}\n\n`;
  }

  // Risk matrix summary
  const criticalCount = topThreats.filter((t) => t.severity === "critical").length;
  const highCount = topThreats.filter((t) => t.severity === "high").length;

  report +=
    `### Risk Summary\n\n` +
    `- **Total applicable techniques:** ${relevantTechniques.length} of ${tara.total}\n` +
    `- **Top threats shown:** ${topThreats.length}\n` +
    `- **Critical severity:** ${criticalCount}\n` +
    `- **High severity:** ${highCount}\n` +
    `- **Highest NISS score:** ${topThreats[0]?.niss.score ?? "N/A"}\n`;

  return {
    content: [{ type: "text", text: sanitizeReport(report + DISCLAIMER) }],
  };
}
